export const elements = {
  app: document.getElementById('app'),
  header: document.getElementById('mobile-header'),
  activeTabName: document.getElementById('active-tab-name'),
  headerActions: document.getElementById('headerActions'),
  langToggleBtn: document.getElementById('langToggleBtn'),
  syncCtaText: document.getElementById('syncCtaText'),
  logoutBtn: document.getElementById('logoutBtn'),
  deleteAccountBtn: document.getElementById('deleteAccountBtn'),
  showMeditationsToggle: document.getElementById('showMeditationsToggle'),
  showNotebookToggle: document.getElementById('showNotebookToggle'),
  showFocusToggle: document.getElementById('showFocusToggle'),
  showAmbientToggle: document.getElementById('showAmbientToggle'),
  navFocus: document.getElementById('navFocus'),
  navAmbient: document.getElementById('navAmbient'),
  
  // Focus
  focusSetup: document.getElementById('focusSetup'),
  focusActive: document.getElementById('focusActive'),
  sessionNamesList: document.getElementById('sessionNamesList'),
  focusWorkInput: document.getElementById('focusWorkInput'),
  focusBreakInput: document.getElementById('focusBreakInput'),
  focusSetsInput: document.getElementById('focusSetsInput'),
  focusSetsVal: document.getElementById('focusSetsVal'),
  focusStartSessionBtn: document.getElementById('focusStartSessionBtn'),
  activeSessionName: document.getElementById('activeSessionName'),
  focusSetCounter: document.getElementById('focusSetCounter'),
  focusTimeline: document.getElementById('focusTimeline'),
  timerLiquid: document.getElementById('timerLiquid'),
  focusTimeDisplay: document.getElementById('focusTimeDisplay'),
  focusStatusLabel: document.getElementById('focusStatusLabel'),
  focusToggleBtn: document.getElementById('focusToggleBtn'),
  focusStopBtn: document.getElementById('focusStopBtn'),
  todoForm: document.getElementById('todoForm'),
  todoInput: document.getElementById('todoInput'),
  todoList: document.getElementById('todoList'),
  todoCount: document.getElementById('todoCount'),
  focusConfirmModal: document.getElementById('focusConfirmModal'),
  focusConfirmCancel: document.getElementById('focusConfirmCancel'),
  focusConfirmFinish: document.getElementById('focusConfirmFinish'),

  // Ambient
  ambientList: document.getElementById('ambientList'),
  ambientMasterVolume: document.getElementById('ambientMasterVolume'),
  ambientDroneToggle: document.getElementById('ambientDroneToggle'),
  ambientActiveOverlay: document.getElementById('ambientActiveOverlay'),
  atmosVisualBg: document.getElementById('atmosVisualBg'),
  atmosTitle: document.getElementById('atmosTitle'),
  atmosStatus: document.getElementById('atmosStatus'),
  atmosVolume: document.getElementById('atmosVolume'),
  exitAtmosBtn: document.getElementById('exitAtmosBtn'),
  atmosParticles: document.getElementById('atmosParticles'),
  
  get views() { return document.querySelectorAll('.view'); },
  
  // Auth
  viewAuth: document.getElementById('view-auth'),
  tabLogin: document.getElementById('tabLogin'),
  tabRegister: document.getElementById('tabRegister'),
  tabsPill: document.getElementById('tabs-pill'),
  authForm: document.getElementById('authForm'),
  emailInput: document.getElementById('emailInput'),
  passwordInput: document.getElementById('passwordInput'),
  nameInput: document.getElementById('nameInput'),
  authError: document.getElementById('authError'),
  authSubmitBtn: document.getElementById('authSubmitBtn'),
  skipAuthBtn: document.getElementById('skipAuthBtn'),
  authLegalGroup: document.getElementById('authLegalGroup'),
  legalCheckbox: document.getElementById('legalCheckbox'),

  // Somatic & Grid
  viewSomaticEntry: document.getElementById('view-somatic-entry'),
  somaticContainer: document.getElementById('somaticContainer'),
  somaticNextBtn: document.getElementById('somaticNextBtn'),
  viewAffectGrid: document.getElementById('view-affect-grid'),
  gridTouchArea: document.getElementById('grid-touch-area'),
  suggestionDot: document.getElementById('suggestion-dot'),
  userDot: document.getElementById('user-dot'),
  gridNextBtn: document.getElementById('gridNextBtn'),
  viewEmotionRefinement: document.getElementById('view-emotion-refinement'),
  emotionRefinementContainer: document.getElementById('emotionRefinementContainer'),
  emotionNextBtn: document.getElementById('emotionNextBtn'),

  // Dashboard
  greetingText: document.getElementById('greetingText'),
  startCheckinBtn: document.getElementById('startCheckinBtn'),
  historyList: document.getElementById('historyList'),
  weeklyTimeline: document.getElementById('weeklyTimeline'),
  weeklyInsight: document.getElementById('weeklyInsight'),
  insightText: document.getElementById('insightText'),
  weeklyExercise: document.getElementById('weeklyExercise'),
  insightExText: document.getElementById('insightExText'),
  weeklyEmpty: document.getElementById('weeklyEmpty'),
  
  // Vagal Heatmap
  vagalHeatmapCard: document.getElementById('vagalHeatmapCard'),
  vagalBlob: document.getElementById('vagalBlob'),
  vagalTraces: document.getElementById('vagalTraces'),
  get vagalModal() { return document.getElementById('infoModal'); },
  get vagalBackdrop() { return document.getElementById('infoBackdrop'); },
  get vagalModalTitle() { return document.getElementById('infoTitle'); },
  get vagalModalAnalysis() { return document.getElementById('vagalModalAnalysis'); },
  get vagalModalRec() { return document.getElementById('vagalModalRec'); },
  get vagalModalHeatmap() { return document.getElementById('vagalModalHeatmap'); },
  get closeVagalModal() { return document.getElementById('closeInfoBtn'); },

  // Step 1: Picker
  stateCards: document.querySelectorAll('.state-card'),

  // Step 3: Exercise
  exerciseTitle: document.getElementById('exerciseTitle'),
  exerciseMicrocopy: document.getElementById('exerciseMicrocopy'),
  exerciseDesc: document.getElementById('exerciseDesc'),
  exerciseStepIndicator: document.querySelector('#view-exercise .step-indicator'),
  savoringSubmitBtn: document.getElementById('savoringSubmitBtn'),
  skipSavoringBtn: document.getElementById('skipSavoringBtn'),
  breathCircle: document.getElementById('breathCircle'),
  breathInstruction: document.getElementById('breathInstruction'),
  startExerciseBtn: document.getElementById('startExerciseBtn'),
  skipExerciseBtn: document.getElementById('skipExerciseBtn'),

  // Step 4: Savoring & Marination
  marPhase1: document.getElementById('marPhase1'),
  marPhase2: document.getElementById('marPhase2'),
  marPhaseOffer: document.getElementById('marPhaseOffer'),
  offerContinueBtn: document.getElementById('offerContinueBtn'),
  offerDoneBtn: document.getElementById('offerDoneBtn'),
  marPhaseScan: document.getElementById('marPhaseScan'),
  scanExitBtn: document.getElementById('scanExitBtn'),
  scanText: document.getElementById('scanText'),
  marPhase3: document.getElementById('marPhase3'),
  marContinueBtn: document.getElementById('marContinueBtn'),
  marSensationContainer: document.getElementById('marSensationContainer'),
  marinationHUD: document.getElementById('marinationHUD'),
  savoringForm: document.getElementById('savoringForm'),
  savoringInput: document.getElementById('savoringInput'),
  savoringInfoBtn: document.getElementById('savoringInfoBtn'),

  // Step 2.5: Meditation Loading
  viewMeditationLoading: document.getElementById('view-meditation-loading'),
  meditationLoadingTitle: document.getElementById('meditationLoadingTitle'),
  loadingCircleProgress: document.getElementById('loadingCircleProgress'),
  skipLoadingBtn: document.getElementById('skipLoadingBtn'),

  // Onboarding
  onbSkipBtn: document.getElementById('onbSkipBtn'),
  onbLetsGoBtn: document.getElementById('onbLetsGoBtn'),
  onbScreensContainer: document.getElementById('onbScreensContainer'),

  // Completion
  returnHomeBtn: document.getElementById('returnHomeBtn'),
  globalHUD: document.getElementById('globalHUD'),
  globalHUDBtn: document.getElementById('globalHUDBtn'),

  // Notifications
  notifToggleCheckbox: document.getElementById('notifToggleCheckbox'),
  nudgeTimeContainer: document.getElementById('nudgeTimeContainer'),
  nudgeTimePicker: document.getElementById('nudgeTimePicker'),
  notifModal: document.getElementById('notifModal'),
  notifAcceptBtn: document.getElementById('notifAcceptBtn'),
  notifDenyBtn: document.getElementById('notifDenyBtn'),

  // Cockpit / Profile
  auraCoreSphere: document.getElementById('aura-core-sphere'),
  userDisplayName: document.getElementById('user-display-name'),
  identityRank: document.getElementById('identity-rank'),
  uniqueDaysStats: document.getElementById('unique-days-stats'),
  identityBadges: document.getElementById('identity-badges'),
  guestCtaBox: document.getElementById('guest-cta-box'),
  guestCtaRegisterBtn: document.getElementById('guest-cta-register-btn'),
  hapticToggle: document.getElementById('hapticToggle'),
  droneToggle: document.getElementById('droneToggle'),
  volumeSlider: document.getElementById('volumeSlider'),
  volumeValLabel: document.getElementById('volume-val-label'),
  uiSoundsToggle: document.getElementById('uiSoundsToggle'),
  exportJsonBtn: document.getElementById('exportJsonBtn'),
  exportTxtBtn: document.getElementById('exportTxtBtn'),
  resetMemoryBtn: document.getElementById('resetMemoryBtn'),
  settingsLoginBtn: document.getElementById('settingsLoginBtn'),
  
  // Scientific Info Modal
  get infoModal() { return document.getElementById('infoModal'); },
  get infoBackdrop() { return document.getElementById('infoBackdrop'); },
  get closeInfoBtn() { return document.getElementById('closeInfoBtn'); },
  get infoIcon() { return document.getElementById('infoIcon'); },
  get infoTitle() { return document.getElementById('infoTitle'); },
  get infoBody() { return document.getElementById('infoBody'); },
  get infoRef() { return document.getElementById('infoRef'); },
  globalInfoBtn: document.getElementById('globalInfoBtn'),
  globalMuteBtn: document.getElementById('globalMuteBtn'),
  muteIconOn: document.getElementById('muteIconOn'),
  muteIconOff: document.getElementById('muteIconOff'),

  // Navigation
  mobileNav: document.getElementById('mobile-nav'),
  get desktopNav() { return document.getElementById('desktop-header-nav'); },
  get navLinks() { return document.querySelectorAll('.nav-link, .desktop-links .nav-item'); },
  get navItems() { return document.querySelectorAll('.mobile-nav .nav-item, .desktop-links .nav-item'); },
  navHome: document.getElementById('navHome'),
  navMeditations: document.getElementById('navMeditations'),
  navNotebook: document.getElementById('navNotebook'),
  navInsight: document.getElementById('navInsight'),
  navProfile: document.getElementById('navProfile'),

  get historyList() { return document.getElementById('historyList'); },
  // Community Modal
  get communityModal() { return document.getElementById('communityModal'); },
  get communityBackdrop() { return document.getElementById('communityBackdrop'); },
  get closeCommunityBtn() { return document.getElementById('closeCommunityBtn'); },
  get commTabBtns() { return document.querySelectorAll('.comm-tab-btn'); },
  get commTabPanes() { return document.querySelectorAll('.comm-tab-pane'); },
  commTabVeri: document.getElementById('commTabVeri'),
  personalStatsGrid: document.getElementById('personalStatsGrid'),
  galaxyCanvas: document.getElementById('galaxyCanvas'),
  commCheckinCount: document.getElementById('commCheckinCount'),
  distVentral: document.getElementById('distVentral'),
  distSympathetic: document.getElementById('distSympathetic'),
  distDorsal: document.getElementById('distDorsal'),
  commTopProtocol: document.getElementById('commTopProtocol'),
  commActiveNow: document.getElementById('commActiveNow'),
  exportJsonBtnModal: document.getElementById('exportJsonBtnModal'),
  exportTxtBtnModal: document.getElementById('exportTxtBtnModal'),
  resetMemoryBtnModal: document.getElementById('resetMemoryBtnModal'),

  // Meditations View
  meditationsList: document.getElementById('meditationsList'),
  filterChips: document.getElementById('filterChips'),
  recommendationsContainer: document.getElementById('recommendationsContainer'),

  // Notebook View
  notebookEntries: document.getElementById('notebookEntries')
};
